- name: Apt install CUDA & NCCL libraries
  apt:
    pkg:
      - cuda-toolkit-11-8
      - libnccl2=2.15.5-1+cuda11.8
      - libnccl-dev=2.15.5-1+cuda11.8
  when: ansible_os_family == "Debian"

- name: Yum install CUDA & NCCL libraries
  package:
    name:
      - libnccl-2.15.1-1+cuda11.8
      - libnccl-devel-2.15.1-1+cuda11.8
      - libnccl-static-2.15.1-1+cuda11.8
      - libcudnn8-8.9.6.50-1.cuda11.8
      - cuda-toolkit-11-8
  when: ansible_os_family == "RedHat"

- name: Set HOROVOD_GPU_OPERATIONS var
  set_fact:
    horovod_install_env_vars: "{{ horovod_install_env_vars | combine({'HOROVOD_GPU_OPERATIONS': 'NCCL'}) }}"

- name: Set HOROVOD_NCCL_INCLUDE and HOROVOD_NCCL_LIB vars
  set_fact:
    horovod_install_env_vars: "{{ horovod_install_env_vars | combine({'HOROVOD_NCCL_INCLUDE': '/usr/include', 'HOROVOD_NCCL_LIB': '/usr/lib64'}) }}"
  when: ansible_os_family == "RedHat"