- name: Install epel in RedHat
  package:
    name: epel-release

- name: Install system dependencies in RedHat
  package:
    name:
      - python3
      - python3-devel
      - gcc
      - gcc-c++
      - make
      - cmake
      - python3-pip
      - openmpi
      - openmpi-devel

- name: Set openmpi in PATH for RedHat
  set_fact:
    horovod_install_env_vars: "{{ horovod_install_env_vars | combine({'PATH': ansible_env.PATH + ':/usr/lib64/openmpi/bin'}) }}"
